export const ROUTES = {
    MAIN: '/',
    CONVERTER: '/converter'
};

export const actionTypes = {
    GET_ALL_CURRENCIES_START: 'GET_ALL_CURRENCIES_START',
    GET_ALL_CURRENCIES_SUCCESS: 'GET_ALL_CURRENCIES_SUCCESS',
    GET_ALLCURRENCIESS_FAILURE: 'GET_ALL_CURRENCIES_FAILURE',
}